services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.5.0
    container_name: homeassistant
    restart: unless-stopped
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - homeassistant_config:/config
    environment:
      - TZ=Europe/Berlin
    networks:
      proxy:
      lan:
        ipv4_address: 192.168.11.12
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.tlandsberger.de`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure,cloudflare"
      - "traefik.http.routers.homeassistant.service=homeassistant"
      - "traefik.http.routers.homeassistant.tls.certresolver=letsencrypt"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      - "traefik.http.routers.vacuumrobot.rule=Host(`vacuum-robot.tlandsberger.de`)"
      - "traefik.http.routers.vacuumrobot.entrypoints=websecure,cloudflare"
      - "traefik.http.routers.vacuumrobot.service=vacuumrobot"
      - "traefik.http.routers.vacuumrobot.tls.certresolver=letsencrypt"
      - "traefik.http.services.vacuumrobot.loadbalancer.server.url=http://vacuum-robot.fritz.box"
      - "traefik.docker.network=proxy"

  mosquitto:
    image: eclipse-mosquitto:2.1.2-alpine
    container_name: mosquitto
    restart: unless-stopped
    entrypoint:
      - /bin/sh
      - -c
      - |
        : > /tmp/passwd
        mosquitto_passwd -b /tmp/passwd ${MQTT_USER} ${MQTT_PASSWORD}
        exec mosquitto -c /mosquitto/config/mosquitto.conf
    configs:
      - source: mosquitto_config
        target: /mosquitto/config/mosquitto.conf
    volumes:
      - mosquitto_data:/mosquitto/data
    environment:
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    ports:
      - "1883:1883"
    networks:
      - proxy

configs:
  mosquitto_config:
    content: |
      listener 1883 0.0.0.0
      allow_anonymous false
      password_file /tmp/passwd
      persistence true
      persistence_location /mosquitto/data/
      log_dest stdout

volumes:
  homeassistant_config:
  mosquitto_data:

networks:
  proxy:
    external: true
    name: proxy
  lan:
    driver: macvlan
    driver_opts:
      parent: enp87s0
    ipam:
      config:
        - subnet: 192.168.11.0/24
          gateway: 192.168.11.1
          ip_range: 192.168.11.12/32
