services:
  cloudflared:
    image: cloudflare/cloudflared:2026.3.0
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --metrics 0.0.0.0:60123 run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - proxy
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=cloudflared:60123"

networks:
  proxy:
    external: true
    name: proxy
