services:
  authentik_db:
    image: postgres:18.3-alpine
    container_name: authentik_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=authentik
      - POSTGRES_USER=authentik
      - POSTGRES_PASSWORD=${AUTHENTIK_DB_PASSWORD}
    volumes:
      - authentik_db_data:/var/lib/postgresql
    networks:
      - authentik

  authentik_server:
    image: ghcr.io/goauthentik/server:2026.2.2
    container_name: authentik_server
    restart: unless-stopped
    command: server
    environment:
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_POSTGRESQL__HOST=authentik_db
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_DB_PASSWORD}
    volumes:
      - authentik_media:/media
      - authentik_templates:/templates
    depends_on:
      - authentik_db
    networks:
      - authentik
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik.rule=Host(`auth.tlandsberger.de`)"
      - "traefik.http.routers.authentik.entrypoints=websecure,cloudflare"
      - "traefik.http.routers.authentik.tls.certresolver=letsencrypt"
      - "traefik.http.services.authentik.loadbalancer.server.port=9000"
      - "traefik.docker.network=proxy"
      - "prometheus.scrape=true"
      - "prometheus.port=authentik_server:9300"

  authentik_worker:
    image: ghcr.io/goauthentik/server:2026.2.2
    container_name: authentik_worker
    restart: unless-stopped
    command: worker
    environment:
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_POSTGRESQL__HOST=authentik_db
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_DB_PASSWORD}
    volumes:
      - authentik_media:/media
      - authentik_templates:/templates
    depends_on:
      - authentik_db
    networks:
      - authentik

volumes:
  authentik_db_data:
  authentik_media:
  authentik_templates:

networks:
  authentik:
    driver: bridge
  proxy:
    external: true
    name: proxy
