services:
  keycloak_db:
    image: postgres:18.3-alpine
    container_name: keycloak_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_db_data:/var/lib/postgresql
    networks:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    container_name: keycloak
    restart: unless-stopped
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=temp-admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=temp-admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KC_HOSTNAME=login.tlandsberger.de
      - KC_HOSTNAME_STRICT=true
      - KC_HOSTNAME_STRICT_HTTPS=true
      - KC_HTTP_ENABLED=true
      - KC_PROXY_HEADERS=xforwarded
      - KC_PROXY_TRUSTED_ADDRESSES=172.18.0.0/16
      - KC_SHUTDOWN_DELAY=30s
    command: start
    depends_on:
      - keycloak_db
    networks:
      - keycloak
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak-public.rule=Host(`login.tlandsberger.de`) && (PathPrefix(`/realms/`) || PathPrefix(`/resources/`) || PathPrefix(`/.well-known/`))"
      - "traefik.http.routers.keycloak-public.entrypoints=websecure,cloudflare"
      - "traefik.http.routers.keycloak-public.tls.certresolver=letsencrypt"
      - "traefik.http.routers.keycloak-public.priority=10"
      - "traefik.http.routers.keycloak-admin.rule=Host(`login.tlandsberger.de`) && PathPrefix(`/admin/`)"
      - "traefik.http.routers.keycloak-admin.entrypoints=websecure,cloudflare"
      - "traefik.http.routers.keycloak-admin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.keycloak-admin.priority=20"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
      - "prometheus.scrape=true"
      - "prometheus.port=keycloak:8080"

volumes:
  keycloak_db_data:

networks:
  keycloak:
    driver: bridge
  proxy:
    external: true
    name: proxy
